name: Build and Run Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Container
        run: |
          docker build -t my-container .
          docker run my-container
