name: Build and Publish Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/lab4:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/lab4:latest

      - name: Set visibility to public
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.CR_PAT }}" \
            https://api.github.com/orgs/vmfx/packages/container/lab4%2Flab4/versions/latest \
            -d '{"visibility":"public"}'
